[package]
name = "comment-errors"
version = "0.1.0"
authors = ["Basile Henry <bjm.henry@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.27"
quote = "1.0.9"
regex = "1.5.4"
syn = { version = "1.0.73", features = ["full", "extra-traits", "fold"] }
