[package]
name = "no-one-understands-my-vine-references-so-i-made-this-programming-language"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4"
