#!/bin/bash

# helper script for compiling and running Haskell programs

d=`dirname $0`

ghc -x hs -o "$d/.polygluttonHS" "$1" -no-keep-hi-files -no-keep-o-files > /dev/null
"$d/.polygluttonHS" ${@:2}
e=$?
rm -f "$d/.polygluttonHs"
exit $e