// example: the m function

set($-1 5)
print(m("$-1"))
print(m("1 + 3"))
print(m("1 * 3"))
print(m("1 - 3"))
print(m("1 + 3 * 2"))
print(m("(1 + 3) * 2"))
print(m("1 * 3 + 2"))
print(m("6 / 3"))
print(m("3 ^ 2"))
print(m("1 < 3"))
print(m("1 > 3"))
print(m("1 == 3"))
print(m("1 != 3"))
print(m("1 <= 3"))
print(m("1 >= 3"))
print(m("3 < 3"))
print(m("3 > 3"))
print(m("3 == 3"))
print(m("3 != 3"))
print(m("3 <= 3"))
print(m("3 >= 3"))
print(m("abs(2)"))
print(m("abs(-2)"))
print(m("sqrt(25)"))
print(m("tan(2)"))
print(m("tan(3)"))
print(m("rand()"))
print(m("rand()"))
print(m("rand()"))
print(m("rand()"))
