[[function]]
name = "main"
body = [
    { comment = ["this is my program"] },
    { put = ["Hello, world"] },
    { puts2 = [] },
]

[[function]]
name = "puts2"
body = [
    { put = ["Hello, world 2"] },
]
