py_project(
    name = "lilith",
    main = "src/python/lilith/__main__.py",
    lib_deps = [
        py_requirement("lark"),
        py_requirement("pyyaml"),
        py_requirement("markdown"),
    ],
    main_deps = [
        py_requirement("prompt-toolkit"),
    ],
    test_deps = [
        py_requirement("hypothesis"),
    ],
)
