[package]
name = "langjam"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gc = { version = "0.4.1", features = ["derive"] }
joinery = "2.1.0"
qp-trie = "0.7.7"
rand = "0.8.4"