
(*----------------------------------------------------*)
(* This code is generated by the KerLang compiler and *)
(* is not intended to be manually edited              *)
(*----------------------------------------------------*)

let f = (fun x0 x1 x2 -> 
  ((-) 
    (( * ) 
      x0
      x1)
    x2))
let g = (fun x0 x1 -> 
  (( * ) 
    (f 
      x0
      42
      x1)
    (f 
      x0
      42
      x1)))
let equals_10 = (fun x0 -> 
  if 0 <> (
    ((-) 
      x0
      10))
  then
    0
  else
    1)
let gap_sum = (fun x0 x1 -> 
  ((+) 
    ((-) 
      x0
      10)
    x1))
let nani = (fun x0 -> 
  ((+) 
    ((+) 
      3
      7)
    x0))
let main = 
  8
let () = main

