
r"""-------------------------------------------------\
| This code is generated by the KerLang compiler and |
| is not intended to be manually edited              |
\--------------------------------------------------"""

def out(x0, x1):
    print(x0)
    return x1

f = (lambda x0, x1, x2: (lambda x0, x1: x0 - x1)((lambda x0, x1: x0 * x1)(x0, x1), x2))
g = (lambda x0, x1: (lambda x0, x1: x0 * x1)(f(x0, 42, x1), f(x0, 42, x1)))
equals_10 = (lambda x0: (0 if (lambda x0, x1: x0 - x1)(x0, 10) else 1))
gap_sum = 0
